spring:
  application:
    name: UberServiceDiscovery

server:
  port: 8761

eureka:
  instance:
    hostname: my-registry
  client:
    register-with-eureka: false
    fetch-registry: false
#    serviceUrl:
#      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/